-- FETCH RECORDS WHERE THERE ARE ORDERS FOR 3 CONSECUTIVE DAYS

DROP TABLE IF EXISTS ORDERS;
CREATE TABLE ORDERS 
(
  ORDER_ID VARCHAR(20) PRIMARY KEY,
  ORDER_DATE DATE NOT NULL
);
DELETE FROM ORDERS;

INSERT INTO ORDERS
VALUES 
('ORD1001', '2021-Jan-01'),
('ORD1002', '2021-Feb-01'),
('ORD1003', '2021-Feb-02'),
('ORD1004', '2021-Feb-03'),
('ORD1005', '2021-Mar-01'),
('ORD1006', '2021-Jun-01'),
('ORD1007', '2021-Dec-25'),
('ORD1008', '2021-Dec-26');

WITH CTE_DIFF AS (SELECT 
  *
  , DATEDIFF(DAY, MIN(ORDER_DATE) OVER(), ORDER_DATE) AS ID
  , ROW_NUMBER() OVER(ORDER BY ORDER_DATE) AS RN
  , DATEDIFF(DAY, MIN(ORDER_DATE) OVER(), ORDER_DATE) - 
    (ROW_NUMBER() OVER(ORDER BY ORDER_DATE))
    AS DIFF
FROM ORDERS)

, CTE_CONS AS (
SELECT
  *
  , COUNT(1) OVER(PARTITION BY DIFF) AS CONS_COUNT
FROM CTE_DIFF
)

SELECT 
  ORDER_ID
  , ORDER_DATE
FROM CTE_CONS
WHERE CONS_COUNT = 3;