/*
------------------
-- TABLES CREATION
------------------

DROP TABLE IF EXISTS TECHTFQ.COMP_Q07_FILES;
CREATE TABLE TECHTFQ.COMP_Q07_FILES (
	ID INT PRIMARY KEY,
	DATE_MODIFIED DATE,
	FILE_NAME VARCHAR(50)
	);
INSERT INTO TECHTFQ.COMP_Q07_FILES VALUES (1,   '2021-06-03', 'thresholds.svg');
INSERT INTO TECHTFQ.COMP_Q07_FILES VALUES (2,   '2021-06-01', 'redrag.py');
INSERT INTO TECHTFQ.COMP_Q07_FILES VALUES (3,   '2021-06-03', 'counter.pdf');
INSERT INTO TECHTFQ.COMP_Q07_FILES VALUES (4,   '2021-06-06', 'reinfusion.py');
INSERT INTO TECHTFQ.COMP_Q07_FILES VALUES (5,   '2021-06-06', 'tonoplast.docx');
INSERT INTO TECHTFQ.COMP_Q07_FILES VALUES (6,   '2021-06-01', 'uranian.pptx');
INSERT INTO TECHTFQ.COMP_Q07_FILES VALUES (7,   '2021-06-03', 'discuss.pdf');
INSERT INTO TECHTFQ.COMP_Q07_FILES VALUES (8,   '2021-06-06', 'nontheologically.pdf');
INSERT INTO TECHTFQ.COMP_Q07_FILES VALUES (9,   '2021-06-01', 'skiagrams.py');
INSERT INTO TECHTFQ.COMP_Q07_FILES VALUES (10,   '2021-06-04', 'flavors.py');
INSERT INTO TECHTFQ.COMP_Q07_FILES VALUES (11,   '2021-06-05', 'nonv.pptx');
INSERT INTO TECHTFQ.COMP_Q07_FILES VALUES (12,   '2021-06-01', 'under.pptx');
INSERT INTO TECHTFQ.COMP_Q07_FILES VALUES (13,   '2021-06-02', 'demit.csv');
INSERT INTO TECHTFQ.COMP_Q07_FILES VALUES (14,   '2021-06-02', 'trailings.pptx');
INSERT INTO TECHTFQ.COMP_Q07_FILES VALUES (15,   '2021-06-04', 'asst.py');
INSERT INTO TECHTFQ.COMP_Q07_FILES VALUES (16,   '2021-06-03', 'pseudo.pdf');
INSERT INTO TECHTFQ.COMP_Q07_FILES VALUES (17,   '2021-06-03', 'unguarded.jpeg');
INSERT INTO TECHTFQ.COMP_Q07_FILES VALUES (18,   '2021-06-06', 'suzy.docx');
INSERT INTO TECHTFQ.COMP_Q07_FILES VALUES (19,   '2021-06-06', 'anitsplentic.py');
INSERT INTO TECHTFQ.COMP_Q07_FILES VALUES (20,   '2021-06-03', 'tallies.py');

SELECT * FROM TECHTFQ.COMP_Q07_FILES;

*/

/*
QUESTIONS:

FOR EACH DATE THAT A MODIFICATION WAS MADE,
	-- RETURN THE DATE
	-- THE EXTENSION(S) OF THE FILES THAT WERE MODIFIED THE MOST
	-- AND THE NUMBER OF FILES MODIFIED THAT DATE

IF MORE THAN ONE FILE EXTENSION TIES FOR THE MOST MODIFICATIONS,
RETURN THEM AS COMMA DELIMITED LIST IN REVERSE ALPHABETICAL ORDER
*/


WITH CTE_CNT AS (
SELECT
	DATE_MODIFIED
	, SUBSTRING(
		[FILE_NAME]
		, CHARINDEX('.', [FILE_NAME])+1
		, LEN([FILE_NAME])
	) AS FILE_EXTN
	, COUNT(1) AS MOD_COUNT
FROM TECHTFQ.COMP_Q07_FILES
GROUP BY DATE_MODIFIED, SUBSTRING([FILE_NAME], CHARINDEX('.', [FILE_NAME])+1, LEN([FILE_NAME]))
)

, CTE_MOD_RNK AS (
SELECT
	*
	, DENSE_RANK() OVER(PARTITION BY DATE_MODIFIED ORDER BY MOD_COUNT DESC) AS MOD_RANK
FROM CTE_CNT
)

SELECT
	DATE_MODIFIED
	, STRING_AGG(FILE_EXTN, ', ') WITHIN GROUP (ORDER BY FILE_EXTN DESC) AS EXTNS_MOST_MODIFIED
	, MOD_COUNT
FROM CTE_MOD_RNK
WHERE MOD_RANK = 1
GROUP BY DATE_MODIFIED, MOD_COUNT
ORDER BY DATE_MODIFIED;